### ISSUE TITLE
Cluster API v1.2

### ISSUE THREAD

**Issue by apricote** [kubernetes-sigs/cluster-api-provider-openstack#1282]
Cluster API v1.2 [beta.0] and [beta.1] have already been released, the normal release is scheduled to happen within the next month. We should migrate CAPO to use CAPI v1.2(.0-beta.1), by following the [migration guide for providers](https://release-1-2.cluster-api.sigs.k8s.io/developer/providers/v1.1-to-v1.2.html).

I think it makes sense to split this into three (mostly independant) PRs:

- [x] Update dependencies and implement breaking changes: #1283
- [x] Bump to `rc.0` to fix our conformance tests: #1295 
- [x] Add Server Side Apply markers to our CRDs: #1325
- [x] Migrate logging to `component-base/logs`: #1296 
- [x] Bump to CAPI v1.2 (once released): #1302

/kind feature
/assign
/milestone v0.7
/area dependency

**Comment by apricote** [comment]
All required migration steps are implemented.

/close
